# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a34ddc6e8132b5850bc93e80675d9685b1fc933cf58610eef660d88edb6eedee10257f740f6e74cffbe33f512164bee9e84f3053019d25239008a945ec9a2a

test:
  secret_key_base: 849b8cf9ba7f992c5a82be37daadb5da952e0a5d88ff4677f39cccab31d87588cf4a209db0d30acad52b7cf5ef528fa5c25c17561eb90265b77b254284cf66bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
